// get this key from emailJS
export const config = {
  EMAILJS_USER_ID: "EMAILJS_USER_ID",
  EMAILJS_SERVICE_ID: "EMAILJS_SERVICE_ID",
  EMAILJS_TEMPLATE_ID: "EMAILJS_TEMPLATE_ID",
  APPSCRIPT_URL: "APPSCRIPT_URL",
};
